# Generated by Django 5.0.2 on 2024-05-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_codesnippet_analysis_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='language',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
